// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public',
  },
  global: {
    headers: {},
  },
});

// Helper to set exhibition context for RLS (if using session variables)
export const setExhibitionContext = async (exhibitionId: string) => {
  // Note: For production, you would use Supabase's session variables
  // For now, we filter client-side
  // await supabase.rpc('set_exhibition_context', { exhibition_id: exhibitionId });
};